# -*- coding: utf-8 -*-
"""constructors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1izhrvUOEPCncfQ_qSMEDksBpy2ssOjly
"""

class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def move(self):
        print("Move")

    def draw(self):
        print("Draw")


point = Point(10, 20)
point.x = 11
print(point.x)