# -*- coding: utf-8 -*-
"""emojiconverter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EiWdrb4XHTPLOgLRRl8DGJevieMRjqLQ
"""

message = input(">")
words = list(message)  # Split into characters
emojis={
    ":)":"😊",
    ":(":"😒"
}
output = ""  # Initialize output
for word in words:
  output += emojis.get(word, word) + " "
print(output)  # Print the modified message