# -*- coding: utf-8 -*-
"""Greet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MffSrKCJ4f979cWyjnvWgggLVCWQyZgW
"""

def greet_user(name):
  print(f'Hi {name}!')
  print("Welcome aboard")

print("Start")
greet_user("Jayachandra")
print("Finish")

