# -*- coding: utf-8 -*-
"""oopinpython.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kalfYT7f7ImZ29t_BgujvoMpK3wih-47
"""

class Point:
  def move(self):
    print("move")

  def draw(self):
    print("draw")

    point1=Point()
    point1.x=10
    point1.y=20
    print(point1.x)
    point1.draw()

    point2=Point()
    point2.x=1